### ISSUE TITLE
Array size question

### ISSUE THREAD

**Issue by forty** [Sc00bz/bscrypt#4]
Hello,

I'm just reading code out of curiosity. Shouldn't this be 64 bytes? https://github.com/Sc00bz/bscrypt/blob/main/blake2b.cpp#L73

**Comment by Sc00bz** [comment]
Yes and fixed. Funny thing I've been meaning to replace the BLAKE2b code with a standard library (like https://github.com/BLAKE2/libb2), but then it's no longer cross platform and no longer self contained.

**Comment by forty** [comment]
For what it's worth, I feel self contained and portable is good for the reference implementation. It would also be nice to have docs & test vectors, but I guess it's already tracked here https://github.com/Sc00bz/bscrypt/issues/2 ;)
